.Dd 30 March 2015
.Dt PMJQ 1
.Os
.Sh NAME
.Nm pmjq
.Nd watch and process a job queue
.Sh SYNOPSIS
.Nm
.Op Fl C Ar cpu-limit
.Op Fl o Ar archive-dir
.Ar job-spool
.Sh DESCRIPTION
The
.Nm
utility watches the directory
.Ar job-spool
and executes the scripts that exist in it. Once executed, the script is copied in the directory
.Op archive-dir
if specified.
.Pp The arguments are as follows:
.Bl -tag -width Ds 
.It Fl o
Specify the archive directory, in which executed scripts are copied.
.It Fl C
Specify (as a percentage) a CPU limit. No new job is launched if the current CPU usage is above the limit.
.El
